#############################################################################
# Makefile for building: jingles-qt
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sat Jan 14 19:27:41 2012
# Project:  jingles-qt.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile jingles-qt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Isrc/externals/qslog -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lvlc -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/avobject.cpp \
		src/libvlcmediaplayer.cpp \
		src/main.cpp \
		src/mediaplayerhandler.cpp \
		src/mediaplaylist.cpp \
		src/pushbuttonwithextras.cpp \
		src/externals/qslog/QsDebugOutput.cpp \
		src/externals/qslog/QsLog.cpp \
		src/externals/qslog/QsLogDest.cpp moc_pushbuttonwithextras.cpp
OBJECTS       = avobject.o \
		libvlcmediaplayer.o \
		main.o \
		mediaplayerhandler.o \
		mediaplaylist.o \
		pushbuttonwithextras.o \
		QsDebugOutput.o \
		QsLog.o \
		QsLogDest.o \
		moc_pushbuttonwithextras.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		jingles-qt.pro
QMAKE_TARGET  = jingles-qt
DESTDIR       = 
TARGET        = jingles-qt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: jingles-qt.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile jingles-qt.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile jingles-qt.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/jingles-qt1.0.0 || $(MKDIR) .tmp/jingles-qt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/jingles-qt1.0.0/ && $(COPY_FILE) --parents src/avobject.h src/libvlcmediaplayer.h src/mediaplayerhandler.h src/mediaplayerinterface.h src/mediaplaylist.h src/nullptr.h src/pushbuttonwithextras.h src/externals/qslog/QsDebugOutput.h src/externals/qslog/QsLog.h src/externals/qslog/QsLogDest.h .tmp/jingles-qt1.0.0/ && $(COPY_FILE) --parents src/avobject.cpp src/libvlcmediaplayer.cpp src/main.cpp src/mediaplayerhandler.cpp src/mediaplaylist.cpp src/pushbuttonwithextras.cpp src/externals/qslog/QsDebugOutput.cpp src/externals/qslog/QsLog.cpp src/externals/qslog/QsLogDest.cpp .tmp/jingles-qt1.0.0/ && (cd `dirname .tmp/jingles-qt1.0.0` && $(TAR) jingles-qt1.0.0.tar jingles-qt1.0.0 && $(COMPRESS) jingles-qt1.0.0.tar) && $(MOVE) `dirname .tmp/jingles-qt1.0.0`/jingles-qt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/jingles-qt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_pushbuttonwithextras.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_pushbuttonwithextras.cpp
moc_pushbuttonwithextras.cpp: src/pushbuttonwithextras.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/pushbuttonwithextras.h -o moc_pushbuttonwithextras.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

avobject.o: src/avobject.cpp src/avobject.h \
		src/nullptr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o avobject.o src/avobject.cpp

libvlcmediaplayer.o: src/libvlcmediaplayer.cpp src/libvlcmediaplayer.h \
		src/mediaplayerinterface.h \
		src/nullptr.h \
		src/externals/qslog/QsLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o libvlcmediaplayer.o src/libvlcmediaplayer.cpp

main.o: src/main.cpp src/externals/qslog/QsLog.h \
		src/externals/qslog/QsLogDest.h \
		src/mediaplaylist.h \
		src/libvlcmediaplayer.h \
		src/mediaplayerinterface.h \
		src/nullptr.h \
		src/mediaplayerhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mediaplayerhandler.o: src/mediaplayerhandler.cpp src/mediaplayerhandler.h \
		src/libvlcmediaplayer.h \
		src/mediaplayerinterface.h \
		src/nullptr.h \
		src/externals/qslog/QsLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mediaplayerhandler.o src/mediaplayerhandler.cpp

mediaplaylist.o: src/mediaplaylist.cpp src/mediaplaylist.h \
		src/externals/qslog/QsLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mediaplaylist.o src/mediaplaylist.cpp

pushbuttonwithextras.o: src/pushbuttonwithextras.cpp src/pushbuttonwithextras.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pushbuttonwithextras.o src/pushbuttonwithextras.cpp

QsDebugOutput.o: src/externals/qslog/QsDebugOutput.cpp src/externals/qslog/QsDebugOutput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QsDebugOutput.o src/externals/qslog/QsDebugOutput.cpp

QsLog.o: src/externals/qslog/QsLog.cpp src/externals/qslog/QsLog.h \
		src/externals/qslog/QsLogDest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QsLog.o src/externals/qslog/QsLog.cpp

QsLogDest.o: src/externals/qslog/QsLogDest.cpp src/externals/qslog/QsLogDest.h \
		src/externals/qslog/QsDebugOutput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QsLogDest.o src/externals/qslog/QsLogDest.cpp

moc_pushbuttonwithextras.o: moc_pushbuttonwithextras.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pushbuttonwithextras.o moc_pushbuttonwithextras.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

